Repository Scarecrow37/VanishingGround, pull requests merged in 2025-08, with the labels that each got.

#401 [FIX/VG-28] prefab scene load bug
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
Labels: bug

#404 [FIX/VG-29] AssetID 0 초기화 안되는 버그, 애니메이션 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22010.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22011.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22012.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22014.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Animator.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Animator.h
Labels: bug

#408 [FIX/VG-29] 각종 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
Labels: bug

#409 [FEATURE/VG-32] 프레임 개선 및 렌더 로직 변경
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
  Source/GA6thFinal_Framework/GraphicsEngine/AnimationCore.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/BlendPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/BlendPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/BrightExtractPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/BrightExtractPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/DXRGBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DeferredPBRLitPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DownAndUpSamplingPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DownAndUpSamplingPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/EndlessGridPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/EndlessGridPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.h
  Source/GA6thFinal_Framework/GraphicsEngine/OutLinePass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/OutLinePass.h
  Source/GA6thFinal_Framework/GraphicsEngine/RTPipeline.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderBuilder.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderBuilder.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderTypes.Mappings.generated.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderTypes.generated.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/SkyBoxPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SkyBoxPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI25DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI25DPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI3DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI3DPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/UIPassBase.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UIPassBase.h
  Source/GA6thFinal_Framework/GraphicsEngine/Utility.h
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_x.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_x_uav.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_y.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_y_uav.hlsl
Labels: enhancement

#411 [FIX/VG-29] AssetBrowser 우 클릭 안먹는 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
Labels: bug

#414 [FEATURE/VG-32] Graphics Renderer Editor 기능 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RendererFileEvent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RendererFileEvent.h
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.h
  Source/GA6thFinal_Framework/Shaders/RTShaders.hlsl
Labels: enhancement

#418 [FEATURE/VG-29] 적이 자폭 시 사망 애니메이션을 패스하는 기능 추가 및 각종 버그 및 편의성 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorBuildSettingMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
Labels: bug, enhancement

#423 [FEATURE/VG-180] Monster HP UI 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/CharacterStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStatsComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStatsComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Hp/HpViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Hp/HpViewModel.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
  Source/GA6thFinal_Framework/UserInterfaceModule/Model.h
Labels: enhancement

#426 [FEATURE/VG-29]사운드 프리 알파 버전용 삽입
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22010.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22011.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22012.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#427 [FEATURE/VG-309] Bloom quality up
  Source/GA6thFinal_Framework/GraphicsEngine/BrightExtractPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DownAndUpSamplingPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Module/GaussianBlurModule.h
  Source/GA6thFinal_Framework/GraphicsEngine/OutLinePass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ParticleRibbonPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ParticleSpritePass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ResourceBase.h
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/Shaders/CommonData.hlsli
  Source/GA6thFinal_Framework/Shaders/CommonDefines.hlsli
  Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
  Source/GA6thFinal_Framework/Shaders/ps_blend.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_x.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_y.hlsl
Labels: enhancement

#428 [FEATURE/VG-330] revelation excel pareser 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/OpenXLSXHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/OpenXLSXHelper.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
Labels: enhancement

#430 [FIX/VG-330] 일반 빌드 컴파일 에러 문제 해결
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
Labels: bug

#441 [FEATURE/VG-352] Multi-Threaded Loading
  .github/workflows/create-jira-issue.yml
  Diagram/EditorModuleFlowChart.drawio.svg
  Diagram/GameEngineFlowChart.drawio.svg
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/StaticMeshRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/BaseMesh.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/BaseMesh.h
  Source/GA6thFinal_Framework/GraphicsEngine/CommandController.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/CommandController.h
  Source/GA6thFinal_Framework/GraphicsEngine/CommandSet.h
  Source/GA6thFinal_Framework/GraphicsEngine/DXRGBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Device.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Device.h
  Source/GA6thFinal_Framework/GraphicsEngine/Externs.h
  Source/GA6thFinal_Framework/GraphicsEngine/FBXConverter.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/FBXConverter.h
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsBase.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/Headers.h
  Source/GA6thFinal_Framework/GraphicsEngine/MeshRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/MeshRenderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/Model.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Model.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderTarget.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Resource.h
  Source/GA6thFinal_Framework/GraphicsEngine/ResourceManager.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ResourceManager.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/StructuredBuffer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Texture.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ThreadPool.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ThreadPool.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI25DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI3DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UIPassBase.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UnorderedAccessView.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/VIBuffer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/VIBuffer.h
  Source/GA6thFinal_Framework/GraphicsEngine/ViewManager.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ViewManager.h
  Source/GA6thFinal_Framework/GraphicsEngine/pch.h
  Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
  Source/GA6thFinal_Framework/Shaders/vs_grid.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skeletal_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skeletal_shadow_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_static_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_static_shadow_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_ui_fr.hlsl
Labels: enhancement

#442 [REFACTOR/VG-325] 씬 오브젝트 코드 및 계층 리팩터링
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_Animation.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_Default.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_FBX.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_Prefab.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_Setting.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_Sound.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_File_VFX.png
  Source/GA6thFinal_Framework/GameEngine/Icon/Editor/Icon_Folder.png
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/Structs/AnimationData.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/Structs/AnimationData.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22010.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22011.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22012.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22014.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/EnemyActionBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyWaitTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
  Source/GA6thFinal_Framework/GraphicsEngine/Animator.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Animator.h
Labels: bug, enhancement

#446 [FEATURE/VG-28] 스카이 박스 설정용 메뉴 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Scene/EditorSceneMenu.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
Labels: enhancement

#447 [FEATURE/VG-356] skybox의 ibl과 env 분리
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DeferredPBRLitPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/SkyBox.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SkyBox.h
  Source/GA6thFinal_Framework/GraphicsEngine/SkyBoxPass.cpp
  Source/GA6thFinal_Framework/Shaders/ps_ssr.hlsl
Labels: enhancement
