Repository Scarecrow37/VanishingGround, pull requests merged in 2025-09, with the labels that each got.

#463 [REFACTOR/VG-28] input receiver
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Component/TestComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Component/TestComponent.h
Labels: bug, enhancement

#464 [FiX/VG-29] editor update
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
Labels: bug, enhancement

#467 [FEATURE/VG-29] 게임 뷰 카메라 조작가능하는 기능 추가
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Game/EditorGameMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Game/EditorGameMenu.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/GameView/EditorGameView.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/GameView/EditorGameView.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Tool/EditorTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Context/FileContext.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/Structs/AnimationData.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
Labels: enhancement

#469 [FEATURE] Cascade Shadow Map 기능 개선 및 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/RenderPassData/EditorRenderPassData.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.cpp
Labels: bug, enhancement

#470 [REFACTOR/VG-316] turn mode refactor
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/Base/TurnModeStateBase.cpp
Labels: bug

#475 [FEATURE/VG-29] AssetID로 Guid 반환하는 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
Labels: enhancement

#485 [FIX/VG-375] Fog Anisotropy, Light Shaft Anisotropy 분리 및 preferesces system 초기작업
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/PreferencesSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/PreferencesSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/RenderPassData/EditorRenderPassData.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/EngineCoresModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GraphicsEngine/FogLightInjectionPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsController.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsController.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderTechnique.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/RenderTechnique.h
  Source/GA6thFinal_Framework/GraphicsEngine/SSAOWritePass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/VolumetricFogTechnique.cpp
  Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
  Source/GA6thFinal_Framework/Shaders/cs_light_injection.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gbuffer.hlsl
Labels: enhancement

#488 [DOCUMENT/VG-409] 이미지 메서드 주석 추가 및 수정
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
Labels: documentation, enhancement

#492 [FEATURE/VG-352] 비동기 리소스 로드 방식 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/StaticMeshRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Animation.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Animation.h
  Source/GA6thFinal_Framework/GraphicsEngine/ComputeShader.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ComputeShader.h
  Source/GA6thFinal_Framework/GraphicsEngine/Externs.h
  Source/GA6thFinal_Framework/GraphicsEngine/Font.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Font.h
  Source/GA6thFinal_Framework/GraphicsEngine/GeometryShader.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GeometryShader.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/MeshShader.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/MeshShader.h
  Source/GA6thFinal_Framework/GraphicsEngine/Model.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Model.h
  Source/GA6thFinal_Framework/GraphicsEngine/PixelShader.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/PixelShader.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Resource.h
  Source/GA6thFinal_Framework/GraphicsEngine/ResourceManager.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ResourceManager.h
  Source/GA6thFinal_Framework/GraphicsEngine/Texture.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Texture.h
  Source/GA6thFinal_Framework/GraphicsEngine/ThreadPool.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ThreadPool.h
  Source/GA6thFinal_Framework/GraphicsEngine/VertexShader.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/VertexShader.h
Labels: enhancement

#503 [FEATURE/VG-412] accessory system
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessoryElement/AccessoryElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessoryElement/AccessoryElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/Base/TurnModeStateBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/Base/TurnModeStateBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: bug, enhancement

#505 [FEATURE/VG-410] MVVM 네임스페이스에 at 함수 추가
  Source/GA6thFinal_Framework/UserInterfaceModule/Model.h
Labels: enhancement

#508 [FIX/VG-28] scene gizmo bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.h
Labels: bug

#515 [FIX/VG-28] scene view guizmo bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.cpp
Labels: bug

#519 [FIX/VG-28] prefab bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Play/EditorPlayMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GizmoManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
Labels: bug, enhancement

#522 [FEATURE/VG-375] Fog Color 설정 가능하게 변경(아트 요청 사항)
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/RenderPassData/EditorRenderPassData.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPassDataHelper.h
  Source/GA6thFinal_Framework/GraphicsEngine/FogLightInjectionPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/VolumetricFogTechnique.cpp
  Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
  Source/GA6thFinal_Framework/Shaders/cs_light_injection.hlsl
Labels: enhancement

#523 [FIX/VG-28] is play bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/LogLevel.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/DrawUIComponent/DrawUIComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Utility/SingletonHelper.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.cpp
Labels: bug

#526 [FEATURE/VG-316] excel table system
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/AccessorySystem/AccessorySystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelDataSystem/ExcelDataSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
Labels: enhancement

#528 [FIX/VG-415] UI Bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIBaseComponent.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIComponent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIComponent.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/DrawUIComponent/DrawUIComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/DrawUIComponent/DrawUIComponent.h
Labels: bug, enhancement

#532 [FIX/VG-415] 선택 상태 해제 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.cpp
Labels: bug

#536 [REFACTOR/VG-371] Turn Queue UI 리팩토링
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/Component.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/Component.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/MapPlayerHPView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/MapPlayerHPView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/MonsterHp/MonsterHpView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/PlayerHP/PlayerHPView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/PlayerHP/PlayerHPView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/TurnQueue/TurnQueueViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/TurnQueue/TurnQueueViewModel.h
  Source/GA6thFinal_Framework/UserInterfaceModule/Model.h
Labels: bug, enhancement

#537 [FIX/VG-355] Release 모드에서 실행 안되던 버그 수정
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
Labels: bug

#534 [FEATURE/VG-414] UmCineMotion 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/ParticleEffect/EditorParticleEffectViewer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/Mathf.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/UmCineMotion.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/UmCineMotion.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.h
Labels: bug, enhancement

#538 [FIX/VG-415] UI 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIComponent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIComponent.h
Labels: bug

#539 [FIX/VG-424] Audio 버그 수정
  Source/GA6thFinal_Framework/AudioModule/System.cpp
  Source/GA6thFinal_Framework/AudioModule/System.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
Labels: bug

#541 [FEATURE/VG-421] 루프 재생 기능 추가
  Source/GA6thFinal_Framework/AudioModule/System.cpp
  Source/GA6thFinal_Framework/AudioModule/System.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Manager/AudioManager.h
Labels: enhancement

#554 [FEATURE/VG-377] fade in out 씬마다 추가
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/SceneTransitionComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/TempTransition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/SceneTransition/TempTransition.h
Labels: enhancement

#555 [FEATURE/VG-373] QTE 가이드 버튼 출력 및 각종 버그 픽스
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/Option.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/PreferencesManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/PreferencesManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
Labels: bug, enhancement

#558 [FEATURR/VG-278] 1차 프레임 최적화 (약 30% 향상)
  Source/GA6thFinal_Framework/GraphicsEngine/DXRComputeSkeletalMeshPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DXRDrawPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DXRGBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DownAndUpSamplingPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Enums.h
  Source/GA6thFinal_Framework/GraphicsEngine/ForwardPBRLitPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ForwardPBRLitPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowMapPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI25DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI25DPass_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI3DPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI3DPass_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/VIBuffer.cpp
  Source/GA6thFinal_Framework/Shaders/CommonData.hlsli
  Source/GA6thFinal_Framework/Shaders/CommonStructs.hlsli
  Source/GA6thFinal_Framework/Shaders/cs_light_injection.hlsl
  Source/GA6thFinal_Framework/Shaders/cs_skeletal_skinning.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_dxrgbuffer.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_forward_pbr_lighting.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_x.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gaussianblur_y.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gbuffer.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_gbuffer_masked.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_shadow.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skeletal_forward_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skeletal_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skeletal_shadow_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_skybox.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_static_forward_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_static_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_static_shadow_fr.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_ui_fr.hlsl
Labels: enhancement

#559 [CHORE/VG-373] 무기 애니메이션 딜레이 적용되도록 변경, 에디터 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/EditorTimelineTrackSequencer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/Track/TimelineEventTrack.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Editor/QTEEditor.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Editor/QTEEditor.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Track/QTETrack.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/Track/QTETrack.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
Labels: bug, enhancement

#563 [FIX/VG-432] ui data max 갯수 256->512
  Source/GA6thFinal_Framework/GraphicsEngine/Enums.h
Labels: bug

#568 [FEATURE/VG-431] 컨트롤러 진동 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/InputReciver/InputReceiver.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Input/InputTestComponent.cpp
  Source/GA6thFinal_Framework/InputModule/Adapter.cpp
  Source/GA6thFinal_Framework/InputModule/Adapter.h
  Source/GA6thFinal_Framework/InputModule/Controller.cpp
  Source/GA6thFinal_Framework/InputModule/Controller.h
  Source/GA6thFinal_Framework/InputModule/ControllerTypes.h
  Source/GA6thFinal_Framework/InputModule/Requires.h
Labels: enhancement

#569 [FIX/VG-438] 메쉬 인스턴싱 버그 수정
  Source/GA6thFinal_Framework/GraphicsEngine/GBufferPass.cpp
Labels: bug

#573 [FEATURE/VG-375] audio 음량조절 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/PreferencesSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Audio/TestAudioComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Audio/TestAudioComponent.h
Labels: enhancement

#577 [FEATURE/VG-436] SDF Font
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/SDF/TestSDFTextRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/SDF/TestSDFTextRenderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.h
  Source/GA6thFinal_Framework/GraphicsEngine/Enums.h
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsCore.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/Graphics_Structs.h
  Source/GA6thFinal_Framework/GraphicsEngine/Interface/IGraphicsBase.h
  Source/GA6thFinal_Framework/GraphicsEngine/Interface/ISDFTextRenderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/RenderScene.h
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/Renderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/SDFFont.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SDFFont.h
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextDrawPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextDrawPass.h
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderTypes.Mappings.generated.h
  Source/GA6thFinal_Framework/GraphicsEngine/ShaderTypes.generated.h
  Source/GA6thFinal_Framework/GraphicsEngine/TextDrawPass.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/TextRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/TextRenderer.h
  Source/GA6thFinal_Framework/GraphicsEngine/ThirdParty/include/yyjson/yyjson.c
  Source/GA6thFinal_Framework/GraphicsEngine/ThirdParty/include/yyjson/yyjson.h
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UI2DPass_OIT.h
  Source/GA6thFinal_Framework/GraphicsEngine/UIPassBase_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UIPassBase_OIT.h
  Source/GA6thFinal_Framework/GraphicsEngine/UITechnique.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UITechnique_OIT.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/UITechnique_OIT.h
  Source/GA6thFinal_Framework/GraphicsEngine/UnorderedAccessView.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/VIBuffer.h
  Source/GA6thFinal_Framework/GraphicsEngine/pch.h
  Source/GA6thFinal_Framework/Shaders/CommonDefines.hlsli
  Source/GA6thFinal_Framework/Shaders/Function.hlsli
  Source/GA6thFinal_Framework/Shaders/ps_sdf_font.hlsl
  Source/GA6thFinal_Framework/Shaders/ps_ui_oit.hlsl
  Source/GA6thFinal_Framework/Shaders/vs_sdf_font_fr.hlsl
Labels: enhancement

#578 [FEATURE/VG-434] null체크 추가 및 gi shader 코드 수정(release에서 터지던 것)
  Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Light/PointLight.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/AbandonButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/AbandonNoButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/AbandonYesButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/BackButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/EnableButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/PreferencesButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/TextureLMH.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DepthStencilView.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/DepthStencilView.h
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowPointLight.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/ShadowPointLight.h
  Source/GA6thFinal_Framework/Shaders/ps_bilateral_up_sample.hlsl
Labels: bug
