Repository Scarecrow37/VanishingGround, pull requests merged in 2025-10, with the labels that each got.

#582 [FEATURE/VG-437] BGM 추가 및 Enemy 애니메이션 예외 강화
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UISFXNavigationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/BGMManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22010.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22011.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22012.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyAction/Action/22010_22019/EnemyAction22014.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/UI/QTEUIManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Utility/FadeHelper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Utility/FadeHelper.h
Labels: bug, enhancement

#585 [FIX/VG-415] UI 시스템 수정 및 UIRoot 컴포넌트 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp
Labels: enhancement

#586 [FEATURE/VG-370] combat UI
  .gitignore
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/ImGuiDX12Module.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ExcelParser/ImGuiColumnSheetParser.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ArtifactUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/NewGame.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/QTE/System/QTESystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/LastQTEResultCondition/LastQTEResultCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/LastQTEResultCondition/LastQTEResultCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Condition/PlayerWinCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Condition/PlayerWinCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerWinState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerWinState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Description/DescriptionPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Description/DescriptionPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/ItemDrop/DropArtifacts/DropArtifactsViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/TurnQueue/TurnQueueViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Weapon/WeaponViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Weapon/WeaponViewModel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.h
  Source/GA6thFinal_Framework/GraphicsEngine/SDFFont.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
Labels: bug, enhancement

#588 [FIX/VG-415] UI 네비게이션 시스템 포커스 관리 기능 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UINavigationComponent.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UIRoot.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UISFXNavigationComponent.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Component/UISFXNavigationComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ReturnToMapNavi.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/MainMenuNavigationBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/MainMenuNavigationBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/EnableButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/EnableButton.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/SoundButton.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/TextureLMH.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/Button/TextureLMH.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UINavigation/TempNavigationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UINavigation/TempNavigationComponent.h
Labels: bug

#590 [FEATURE/VG-372] 라이트 세팅을 불러올 수 있는 컴포넌트 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/GraphicsModule.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/Stage.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/ImportGraphicsSetting.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Preferences/ImportGraphicsSetting.h
Labels: enhancement

#595 [FIX/VG-415] 텍스트 사이즈 버그 수정
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
Labels: bug

#597 [FEATURE/VG-415] 글꼴 두께 설정 기능 활성화
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
Labels: enhancement

#598 [FEATURE/VG-444] CombatUIManager에 HUD 화면 좌표 따라가게 좌표 갱신하는 기능 추가
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CharacterHUD/CharactorHUDGroup.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CharacterHUD/CharactorHUDGroup.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
Labels: enhancement

#599 [FIX/VG-444] CombatUIManager 댕글링포인터 접근 수정
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CombatUIManager.h
Labels: bug

#600 [FEATURE/VG-370] combat UI 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/CombatUIManager/CharacterHUD/CharactorHUDGroup.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/RestartStageNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/MainMenuNavigationBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/MainMenuNavigationBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/MainMenu/Quit.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManagerTracker.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/MapManagerTracker.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/PlayerSystem/PlayerSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/PlayerHP/PlayerHPView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/RevelationsView/RevelationsView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Revelations/RevelationsViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/Revelations/RevelationsViewModel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/TurnQueue/TurnQueueViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/TurnQueue/TurnQueueViewModel.h
  Source/GA6thFinal_Framework/GraphicsEngine/SDFFont.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.h
Labels: bug, enhancement

#601 [FIX/VG-28] round once action 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Light/Base/LightComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/RewardPopup.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Map/RewardPopup.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/StageFocusView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Map/StageFocusView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/RevelationsView/RevelationsView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/RevelationsView/RevelationsView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/TurnQueue/TurnQueueView.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Views/Weapon/WeaponView.h
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
Labels: bug, enhancement

#604 [FIX/VG-449] SDFTextRenderer 코드 정리 및 안전성 개선
  Source/GA6thFinal_Framework/GraphicsEngine/SDFTextRenderer.cpp
Labels: bug

#606 [FEATURE/VG-370] item drop system 기능 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/BattleSystem/Battle.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/BattleSystem/Battle.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/Interface/IDropItem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/ItemDropSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ArtifactUIManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ArtifactUIManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UI/ItemDropUIRootManager.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ArtifactButtonNavi.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ItemDropSystem/UINavi/ArtifactButtonNavi.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/ChainCondition/ChainCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Description/DescriptionPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/ItemDrop/DropArtifacts/DropArtifactsViewModel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/ViewModels/ItemDrop/DropArtifacts/DropArtifactsViewModel.h
Labels: bug, enhancement
