Repository Scarecrow37/VanishingGround, pull requests merged in 2025-04, with the labels that each got.

#14 [DOCS] Create versioning action
  .github/workflows/bump-on-develop-merge.yml
  scripts/bump-minor.sh
  scripts/bump-patch.sh
Labels: documentation, enhancement

#15 [FEAT] filesystem
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.h
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorProjectMenu.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorProjectMenu.h
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSceneMenu.h
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSettingMenu.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSettingMenu.h
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorWindowMenu.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorWindowMenu.h
Labels: bug

#17 [FIX] editor
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorDebugView.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorInspectorView.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorMenu/EditorSceneMenu.h
  Source/GA6thFinal_Framework/ProjectVG/Source/EditorTools/EditorSceneView.cpp
Labels: bug

#18 [DOCS] Update bump-on-develop-merge.yml
  .github/workflows/bump-on-develop-merge.yml
Labels: bug, documentation

#19 [FIX] FileObserver 스레드 종료 시 간헐적으로 무한 블로킹하는 현상 수정
  Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.cpp
  Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.h
  Source/GA6thFinal_Framework/FileSystem/FileHelper.h
Labels: bug

#20 [CHORE] 디버그 로그 코드 추가에 대한 풀 리퀘스
  Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.cpp
  Source/GA6thFinal_Framework/FileSystem/Core/FileObserver.h
  Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.cpp
  Source/GA6thFinal_Framework/FileSystem/Core/FileSystem.h
  Source/GA6thFinal_Framework/FileSystem/Extra/FileContext.cpp
  Source/GA6thFinal_Framework/FileSystem/FileHelper.h
  Source/GA6thFinal_Framework/FileSystem/Type/FileDataType.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
Labels: enhancement

#25 [DOCS] Update bump-on-develop-merge.yml
  .github/workflows/bump-on-develop-merge.yml
Labels: bug, documentation

#26 [DOCS] Git Action 및 Issue Template, Pull Request Template develop Branch로 병합
  .github/pull_request_template.md
  .github/workflows/bump-on-develop-merge.yml
  Diagram/GameEngineFlowChart.drawio.svg
  scripts/bump-minor.sh
  scripts/bump-patch.sh
Labels: documentation, enhancement

#27 [FIX] Add if when merged from none
  .github/workflows/bump-on-develop-merge.yml
Labels: bug, documentation

#28 [FIX] Add if when merged from none
  .github/workflows/bump-on-develop-merge.yml
Labels: bug, documentation

#34 [TEST/VG-133] 테스트를 위한 풀 리퀘스트
  Test.txt
Labels: bug, documentation, enhancement

#35 [CI/VG-134] Pull Request Template 수정
  .github/pull_request_template.md
Labels: documentation

#36 [CI/VG-134] Pull-Request 양식 수정
  .github/pull_request_template.md
Labels: documentation

#39 [CI/VG-135] Jira 이슈 생성 Actino 수정
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation, enhancement

#41 [CI/VG-135] Create Task 에서 If 를 안타는 문제
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#43 [CI/VG-135] Task 생성 도중 실패하는 문제 해결
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#45 [CI/VG-135] Issue 제목이 정상적으로 변경되지 않는 문제 해결
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#47 [CI/VG-135] 여전히 제목이 정상적이지 않은 문제 해결
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#49 [CI/VG-135] 한번만 더 해보자
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#52 [CI/VG-135] 실험용...
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#55 [CI/VG-135] 다시 한번 가즈아
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#57 [CI/VG-135] gh 설치법 변경
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#59 [CI/VG-135] Issue Template 변경
  .github/ISSUE_TEMPLATE/bug-issue-form.yml
  .github/ISSUE_TEMPLATE/feature-issue-form.yml
Labels: bug, documentation

#61 [CI/VG-135] 부모 작업 로그 찍기
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#62 [CI/VG-135] 문법 오류 제거
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation

#70 [CI/VG-135] 이거가 정답인가?
  .github/ISSUE_TEMPLATE/issue-form.yml
Labels: bug, documentation

#73 [CI/VG-135] Jira 작업 생성 Script 변경 및 Issue Template 변경
  .github/ISSUE_TEMPLATE/bug-issue-form.yml
  .github/ISSUE_TEMPLATE/feature-issue-form.yml
  .github/ISSUE_TEMPLATE/issue-form.yml
  .github/workflows/create-jira-issue.yml
Labels: bug, documentation, enhancement

#82 [STYLE/VG-157] ColumnLimit 옵션 삭제
  Source/GA6thFinal_Framework/.clang-format
Labels: style

#83 [STYLE/VG-157] Clang-Format Develop에도 적용
  Source/GA6thFinal_Framework/.clang-format
Labels: style

#87 [FEATURE] dx12 렌더 프레임워크 추가.
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderPass.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTarget.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTechnique.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderTechnique.h
Labels: enhancement

#92 [fix/VG-29] 파일 시스템 폴더가 메타 추적 못하는 현상 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileContext.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileContext.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Extra/FileEventNotifier.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Interface/IFileEventProcesser.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.cpp
Labels: bug

#98 [feture/VG-29] 에디터 툴 상태 직렬화 기능 추가
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Window/EditorWindowMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Log/EditorLogsTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AppModule/ImGuiDX12Module.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorDockSpace.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorGui.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorMenuBar.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Setting/EditorSetting.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Setting/EditorSetting.h
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.h
Labels: bug

#102 [fix/VG-239] 파일 Removed 이벤트의 empty Guid반환 오류 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
Labels: bug

#111 [FIX/VG-29] 에디터 포커싱 조작 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
Labels: bug

#114 [fix/VG-29] 드래그 이벤트 스크립트 호환성을 위해 구조 변경
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/DragDropTypes/DragDropAsset.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
Labels: bug

#118 [FIX/VG-261] Scene 재 로드 시 렌더러 컴포넌트에서 터지던 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Graphics/MeshRenderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Graphics/StaticMeshRenderer.cpp
Labels: bug

#123 [FIX/VG-272] Null Guid가 루트 경로를 반환하는 버그 수정.
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileDataType.h
  Source/GA6thFinal_Framework/ProjectVG/ProjectSettings/SceneManager.setting.json
Labels: bug
