Repository Scarecrow37/VanishingGround, pull requests merged in 2025-07, with the labels that each got.

#267 [FEATURE/VG-30] Audio 추가
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Callback/IncreaseGenerationCallback.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Callback/IncreaseGenerationCallback.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Exceptions/AudioExceptions.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Exceptions/AudioExceptions.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Types/AudioTypes.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Types/AudioTypes.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Source/AudioSource.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Source/AudioSource.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
Labels: enhancement

#269 [REFACTOR/VG-322] Input 개선 및 버그 수정
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/ControllerAdapter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/XInput/XInputAdapter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/XInput/XInputAdapter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Declare/Exceptions/InputExceptions.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Declare/Exceptions/InputExceptions.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Declare/InputError.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Devices/Controller/Controller.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Devices/Controller/Controller.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/System/InputSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/System/InputSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
Labels: bug, enhancement

#270 [REFACTOR/VG-32] 에디터 빌드에서 RenderComponent 등록 방식 통일 및 기타 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Animator.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Animator.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/BlendPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Device.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/LightCore.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/LightCore.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/MeshRenderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/MeshRenderer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Light/Base/LightComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.cpp
Labels: bug

#271 [DOCUMENT/VG-30] Audio Summary 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Callback/IncreaseGenerationCallback.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Exceptions/AudioExceptions.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Handle/AudioHandle.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Source/AudioSource.h
Labels: bug, documentation

#272 [FIX/VG-32] GBuffer에서 Shader의 배열에 잘못된 인덱스로 접근하는 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GBufferPass.h
Labels: bug

#274 [REFACTOR/VG-28] scene input refactor
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/HierarchyFindTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/XInput/XInputAdapter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Devices/Controller/Controller.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/Input/InputTestComponent.cpp
Labels: enhancement

#275 [FEAUTRE/VG-29] SkeletalMeshRenderer Animatoion 기능 추가, ModelDetailsTool에 Sequencer Tool 추가 및 기능 개선
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorAnimationNotifyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorAnimationNotifyTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Sequencer/EditorSequencerTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Sequencer/EditorSequencerTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/EditorSequencer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/EditorSequencer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Utillity/EditorDragState.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Utillity/EditorDragState.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Animator.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Animator.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/MeshRenderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/AnimationNotifySet.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/AnimationNotifySet.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/TimelineSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/TimelineSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/MeshComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/StaticMeshRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/StaticMeshRenderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Timeline/AnimationEventListener.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Timeline/AnimationEventListener.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.h
Labels: enhancement

#277 [RELEASE/VG-164] Editor 1.2.0
  Source/GA6thFinal_Framework/Installer/Installer.vdproj
Labels: enhancement

#279 [FIX/VG-28] Scene RayPicker에서 카메라 기준 정렬 안하는 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
Labels: enhancement

#280 [FIX/VG-32] debug 모드가 아닐때도 가능하게 변경
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.h
Labels: bug

#282 [RELEASE/VG-164] Editor v1.2.3
  Source/GA6thFinal_Framework/Installer/Installer.vdproj
Labels: bug

#283 [RELEASE/VG-164] Editor v1.2.3
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.h
  Source/GA6thFinal_Framework/Installer/Installer.vdproj
Labels: bug

#284 [FIX] DebugDraw Release모드에서도 동작하게 변경
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/GraphicsCore.cpp
Labels: bug

#288 [FIX/VG-29] filesystem 터지는 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
Labels: bug

#287 [FEATURE/VG-29] AnimationEventListener Component 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Sequencer/EditorSequencerTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Sequencer/EditorSequencerTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/DebugDrawCore.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/AnimationNotifySet.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/TimelineCore/AnimationNotifySet.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Mesh/SkeletalMeshRenderer.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Timeline/AnimationEventListener.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Timeline/AnimationEventListener.h
Labels: enhancement

#289 [REFACTOR] Input Module Static Library 화
  Source/GA6thFinal_Framework/GA6thFinal_Framework.sln
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Adapter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Adapter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/ControllerAdapter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/ControllerAdapter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Adapter/Controller/XInput/XInputAdapter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/InputCore/Declare/Exceptions/InputExceptions.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/InputModule/Adapter.cpp
  Source/GA6thFinal_Framework/InputModule/Adapter.h
  Source/GA6thFinal_Framework/InputModule/Controller.cpp
  Source/GA6thFinal_Framework/InputModule/Controller.h
  Source/GA6thFinal_Framework/InputModule/ControllerTypes.cpp
  Source/GA6thFinal_Framework/InputModule/ControllerTypes.h
  Source/GA6thFinal_Framework/InputModule/Exceptions.cpp
  Source/GA6thFinal_Framework/InputModule/Exceptions.h
  Source/GA6thFinal_Framework/InputModule/InputModule.h
  Source/GA6thFinal_Framework/InputModule/InputModule.vcxproj
  Source/GA6thFinal_Framework/InputModule/InputModule.vcxproj.filters
  Source/GA6thFinal_Framework/InputModule/Requires.h
  Source/GA6thFinal_Framework/InputModule/pch.cpp
  Source/GA6thFinal_Framework/InputModule/pch.h
  Source/GA6thFinal_Framework/Installer/Installer.vdproj
Labels: enhancement

#290 [FEATURE/VG-317] Weapon Stats 및 Weapon Table 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/WeaponTable/WeaponTableComponent.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#294 [REFACTOR/VG-30] Audio Module Static Library
  Source/GA6thFinal_Framework/AudioModule/AudioModule.h
  Source/GA6thFinal_Framework/AudioModule/AudioModule.vcxproj
  Source/GA6thFinal_Framework/AudioModule/AudioModule.vcxproj.filters
  Source/GA6thFinal_Framework/AudioModule/Callback.cpp
  Source/GA6thFinal_Framework/AudioModule/Callback.h
  Source/GA6thFinal_Framework/AudioModule/Exceptions.cpp
  Source/GA6thFinal_Framework/AudioModule/Exceptions.h
  Source/GA6thFinal_Framework/AudioModule/Handle.cpp
  Source/GA6thFinal_Framework/AudioModule/Handle.h
  Source/GA6thFinal_Framework/AudioModule/Requires.h
  Source/GA6thFinal_Framework/AudioModule/Source.cpp
  Source/GA6thFinal_Framework/AudioModule/Source.h
  Source/GA6thFinal_Framework/AudioModule/System.cpp
  Source/GA6thFinal_Framework/AudioModule/System.h
  Source/GA6thFinal_Framework/AudioModule/Types.cpp
  Source/GA6thFinal_Framework/AudioModule/Types.h
  Source/GA6thFinal_Framework/AudioModule/pch.cpp
  Source/GA6thFinal_Framework/AudioModule/pch.h
  Source/GA6thFinal_Framework/GA6thFinal_Framework.sln
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioManager/AudioManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Callback/IncreaseGenerationCallback.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/Exceptions/AudioExceptions.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/Declare/RIFF/AudioChunk.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
Labels: enhancement

#295 [FEATURE/VG-316] turn system을 위한 player weapon 기능 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStatsComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStatsComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/WeaponTable/WeaponTableComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#296 [FEATURE/VG-316] turn system에 Player Weapon 추가에 따른 기능 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Player/PlayerStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#298 [REFACTOR] Unity Build 적용
  Source/GA6thFinal_Framework/GA6thFinal_Framework.sln
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/ImGuiThirdParty/GraphEditor.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/GraphEditor.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImCurveEdit.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImCurveEdit.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGradient.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGradient.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGuiThirdParty.vcxproj
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGuiThirdParty.vcxproj.filters
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGuizmo.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImGuizmo.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImSequencer.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImSequencer.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/ImZoomSlider.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/crude_json.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/crude_json.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imconfig.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_bezier_math.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_bezier_math.inl
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_canvas.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_canvas.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_demo.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_draw.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_extra_math.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_extra_math.inl
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_dx11.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_dx11.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_dx12.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_dx12.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_win32.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_impl_win32.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_internal.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_node_editor.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_node_editor.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_node_editor_api.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_node_editor_internal.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_node_editor_internal.inl
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_stdlib.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_stdlib.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_tables.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imgui_widgets.cpp
  Source/GA6thFinal_Framework/ImGuiThirdParty/imstb_rectpack.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imstb_textedit.h
  Source/GA6thFinal_Framework/ImGuiThirdParty/imstb_truetype.h
Labels: enhancement

#300 [FEATURE/VG-28] transform world position stay 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
Labels: enhancement

#301 [FEATURE/VG-325] Enemy AI 모델 및 Action 노드 기반 제작
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/AI/EnemyAI.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/AI/EnemyAI.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enum/EnemyEnum.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/Base/EnemyStateBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundEndPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundStartPhase.cpp
Labels: enhancement

#303 [REFACTOR] Game Script Unity Build
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
Labels: enhancement

#306 [FEATURE/VG-316] turn system
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineLogger.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/Condition/GameClearCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/Condition/GameClearCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/Condition/GameOverCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/Condition/GameOverCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameClearState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameClearState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameOverState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameOverState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
Labels: enhancement

#307 [FEATURE/VG-32] 3D UI Draw & Billbord
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Camera.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Enums.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/RenderScene.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Renderer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SpriteRenderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/SpriteRenderer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI25DPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI25DPass.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI2DPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI2DPass.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI3DPass.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UI3DPass.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UIPassBase.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UIPassBase.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UIRenderer.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UIRenderer.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UITechnique.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/UITechnique.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/UI/TestUI.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/UI/TestUI.h
  Source/GA6thFinal_Framework/Shaders/vs_ui_fr.hlsl
Labels: enhancement

#311 [FEATURE/VG-328] TokenSystem 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Interface/ITriggerType.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Timeline/AnimationEventListener.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Interface/IToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Interface/IToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/BleedToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/BleedToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundEndPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundEndPhase.h
Labels: enhancement

#315 [FEATURE/VG-330] 계시 에디터 기능 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/FactoryRegister.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Base/RevelationActionBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Critical/CriticalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Critical/CriticalDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptCore.cpp
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#319 [FEATURE/VG-328] Token 기능 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Interface/ITriggerType.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Interface/IToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Bleed/BleedToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Bleed/BleedToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Poison/PoisonToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Poison/PoisonToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Shock/ShockToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Shock/ShockToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Stun/StunToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Stun/StunToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenInventory.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenInventory.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/EnemyActionPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/PlayerActionPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#325 [FEATURE/VG-29] Command의 Excute 성공 여부 반환 기능을 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DropPrefabCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DropPrefabCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/PackPrefabCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/PackPrefabCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/SetParentCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/SetParentCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/Command/InputAutoCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/UmCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/Command/SequencerCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/Sequencer/Command/SequencerCommand.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.h
Labels: enhancement

#326 [FEATURE/VG-330] revelation system action을 Turn Action 기반으로 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/InputAuto.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Base/RevelationActionBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Critical/CriticalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Critical/CriticalDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Token/TokenApplyAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Token/TokenApplyAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TurnAction/TestActionComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TurnAction/TestActionComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnActionFactory.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#327 [FEATURE/VG-29] File Drag&Drop이벤트 추가, SpriteFontImporter 추가
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/PopupBox/EditorPopupBox.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/Gui/PopupBox/EditorPopupBox.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/System/EditorPopupBoxSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/System/EditorPopupBoxSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Event/FileEventSubscriber.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Importer/SpriteFontImporter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Importer/SpriteFontImporter.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/MeshRenderer.cpp
Labels: bug, enhancement

#338 [FIX/VG-28] ray picker fix
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
Labels: bug

#337 [FIX/VG-335] FileSystem이 Project파일에 Meta파일을 생성하는 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
Labels: bug

#343 [FIX/VG-28] animator resource bug fix
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
Labels: bug

#340 [FEATURE/VG-316] turn action
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/ResourceManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/ResourceManager.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Token/TokenApplyAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationAction/Token/TokenApplyAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/CharacterStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Enemy/EnemyStatsComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Player/PlayerStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Player/PlayerStatsComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/TurnActorStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/TurnAction/TestActionComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Token/TokenApplyAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Token/TokenApplyAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#336 [FIX/VG-336] FBX Converter 애니메이션 이상하게 나오는 현상 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/Enums.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.cpp
Labels: bug

#344 [FEATURE/VG-29] 에디터 버그 및 편의성 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Model/EditorModelMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorBuildSettingMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Project/EditorProjectMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GraphicsCore/FBXConverter.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
Labels: bug, enhancement

#348 [FEATURE/VG-29] 에디터 버그 및 편의성 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/DynamicCamera/EditorDynamicCamera.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Command/EditorCommandTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Debug/EditorDebugTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DetachChildrenCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/FocusCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Inspector/EditorInspectorTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/EditorSceneTool.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/CommandCore/CommandManager.h
Labels: bug, enhancement

#353 [FAETURE/VG-28] deserialize exception 기능
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/Command/DropPrefabCommand.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/ReflectHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EditorCore/EditorModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/YAMLHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/YAMLHelper.h
  Source/GA6thFinal_Framework/GameEngine/ThirdParty/include/UmYaml-cpp.h
Labels: enhancement

#355 [FIX/VG-29] FileSystem 불필요 코드 제거 및 일부 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Menu/Setting/EditorSettingMenu.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Event/FileEventObserver.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Event/FileEventSubscriber.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/FileSystemModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/System/FileSystem.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileData.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileData.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/FileSystem/Type/FileSystemSetting.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/ImguiHelper.h
Labels: bug

#365 [FEATRUE/VG-316] turn action 기능 리팩토링
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ClassCore/Delegate.hpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/dllUtility.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/DamageSystem/DamageSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/ChainCondition/ChainCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/ChainCondition/ChainCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/RoundOnceCondition/RoundOnceCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/TokenCondition/TokenCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/TokenCondition/TokenCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/TurnActionCondition.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/build_debug.bat
  Source/GA6thFinal_Framework/GameScripts/build_debug_editor.bat
  Source/GA6thFinal_Framework/GameScripts/build_release.bat
  Source/GA6thFinal_Framework/GameScripts/build_release_editor.bat
Labels: enhancement

#367 [FEATURE/VG-164] Audio Component 추가
  Source/GA6thFinal_Framework/AudioModule/Callback.cpp
  Source/GA6thFinal_Framework/AudioModule/Callback.h
  Source/GA6thFinal_Framework/AudioModule/System.cpp
  Source/GA6thFinal_Framework/AudioModule/System.h
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/ApplicationCore/Application.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioModule.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/AudioCore/AudioModule.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/EngineCores.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj.filters
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/AudioComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Audio/AudioComponent.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#370 [FEATURE/VG-316] turn system
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Scene/Command/EditorSceneCommands.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/BattleSystem/Battle.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/BattleSystem/Battle.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Camera/CameraComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationElement/RevelationElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/ChainCondition/ChainCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Condition/TokenCondition/TokenCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Critical/CriticalDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/MultiTargetDamage/MultiTargetDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/MultiTargetDamage/MultiTargetDamageAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Token/TokenApplyAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/Token/TokenApplyAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/TurnMode.h
Labels: bug, enhancement

#377 [FEATURE/VG-180] UI 개선
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/UmFramework.h
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PanelSlotComponent/PanelSlotComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PanelSlotComponent/PanelSlotComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PlacementUIComponent/PlacementUIComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PlacementUIComponent/PlacementUIComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/UIComponent/UIComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Anchor/AnchorPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Anchor/AnchorPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Grid/GridPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Grid/GridPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Horizontal/HorizontalPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/UIRoot/UIRoot.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/UIRoot/UIRoot.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Center/CenterWrapper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Center/CenterWrapper.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Padding/PaddingWrapper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Padding/PaddingWrapper.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#378 [FEATURE/VG-29] Model Editor에서 Bone계층을 간략하게 확인할 수 있는 기능 추가
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj
  Source/GA6thFinal_Framework/GameEngine/GameEngine.vcxproj.filters
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/AssetBrowser/EditorAssetBrowserTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorAnimationNotifyTool.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelDetails.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelHierarchy.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelHierarchy.h
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelInspector.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Model/EditorModelInspector.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/Utility/FileHelper.h
  Source/GA6thFinal_Framework/GraphicsEngine/Enums.h
  Source/GA6thFinal_Framework/ProjectVG/Source/Application/GameApplication.cpp
Labels: enhancement

#379 [FEATURE/VG-317] alpha weapon
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/RevelationSystem/RevelationSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/Weapon/WeaponStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/AdditionalDamage/AdditionalDamageAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnAction/TurnAction.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Player.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponElement/WeaponElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/WeaponSystem/WeaponTable/WeaponTableComponent.h
Labels: enhancement

#384 [FEATURE/VG-316] 프리프리 알파 character animation 수정
  Source/GA6thFinal_Framework/GameEngine/project_build_debug.bat
  Source/GA6thFinal_Framework/GameEngine/project_build_release.bat
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Condition/EnemyDeadCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/Condition/PlayerDeadCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerDeadState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/GameClearState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/RoundStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/TurnListEmptyState.cpp
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#385 [FEATURE/VG-180] UI 개선 및 Component 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/EditablePlacementUIComponent/EditablePlacementUIComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/EditablePlacementUIComponent/EditablePlacementUIComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PanelSlotComponent/PanelSlotComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PanelSlotComponent/PanelSlotComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PlacementUIComponent/PlacementUIComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/PlacementUIComponent/PlacementUIComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Base/UIComponent/UIComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Dummy/DummyElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Anchor/AnchorPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Anchor/AnchorPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Grid/GridPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Grid/GridPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Horizontal/HorizontalPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Horizontal/HorizontalPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/UIRoot/UIRoot.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/UIRoot/UIRoot.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Center/CenterWrapper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Center/CenterWrapper.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Padding/PaddingWrapper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Padding/PaddingWrapper.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#386 [FEATURE/VG-328] 기절 Token 추가, Enemy Action 자폭 추가
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/AnimationComponent.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Animation/Structs/AnimationData.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyActionSystem/EnemyActionSystem.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/EnemyActionSystem/EnemyActionSystem.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Stats/CharacterStats.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Interface/IToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Stun/StunToken.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Object/Stun/StunToken.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/Token.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/Token/TokenInventory.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22000.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22000.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22001.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22001.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22002.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22002.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22003.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22003.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22004.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22000_22009/EnemyAction22004.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22010.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22010.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22011.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22011.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22012.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22012.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22013.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22013.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22014.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/22010_22019/EnemyAction22014.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/AnemyActionBase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Action/AnemyActionBase.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/Enemy.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Enemy/State/EnemyPlayTurnState.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/TurnActor.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/Condition/CheckTurnEndCondition.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/CombatStartPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/EnemyActionPhase.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnMode/State/PlayerActionPhase.cpp
Labels: bug, enhancement

#393 [FEATURE/VG-180] UI 추가
  Source/GA6thFinal_Framework/GameEngine/Source/Editor/Tool/Hierarchy/EditorHierarchyTool.cpp
  Source/GA6thFinal_Framework/GameScripts/GameScripts.vcxproj
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Image/ImageElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Elements/Text/TextElement.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Description/DescriptionPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Description/DescriptionPanel.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Panels/Horizontal/HorizontalPanel.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Ratio/RatioWrapper.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/UI/Wrappers/Ratio/RatioWrapper.h
  Source/GA6thFinal_Framework/GameScripts/UmScriptsExport.h
Labels: enhancement

#394 [FEATURE/VG-316] turn log output
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/FPSCounter.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.cpp
  Source/GA6thFinal_Framework/GameScripts/Scripts/Test/DevTools/LogOutput.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/Player/State/PlayerPlayTurnState.cpp
  Source/GA6thFinal_Framework/GameScripts/build_debug.bat
  Source/GA6thFinal_Framework/GameScripts/build_debug_editor.bat
  Source/GA6thFinal_Framework/GameScripts/build_release.bat
  Source/GA6thFinal_Framework/GameScripts/build_release_editor.bat
Labels: enhancement

#395 [FEATURE/VG-28] 프리팹 및 Transform 버그 수정
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/ComponentFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/SceneManager.h
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/GameObject/GameObject.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
  Source/GA6thFinal_Framework/GameScripts/Scripts/TurnSystem/TurnActor/Character/CharacterBase.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsBase.cpp
  Source/GA6thFinal_Framework/GraphicsEngine/GraphicsBase.h
Labels: bug, enhancement

#396 Refactor/vg 28/game object refactor
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/EngineCore/GameObjectFactory.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.cpp
  Source/GA6thFinal_Framework/GameEngine/Source/Engine/GameCore/Transform/Transform.h
Labels: bug
